### ISSUE TITLE
Door open and close repeatedly

### ISSUE THREAD

**Issue by macnam216** [MTK911/Zkteco-F18-Doorunlock#1]
My device is Zkteco F18. Im using the code in eXp.py file to open it ( its work very well )  and i send many open commands to my device ( both when the door is closed and when it is open). However, it seems that these commands are not executed immediately but are queued. Then, when the door closes, it starts opening and closing repeatedly, Is there any way i can fix this situation ?

**Comment by MTK911** [comment]
@macnam216 sorry for I no longer have access to the hardware or recollection of its working as it was a while ago and I was only having fun.
